version: '3.1'
services:
  css:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - "30015:30015/tcp"
      - "30015:30015/udp"
      - "30020:30020/udp"
      - "30005:30005/udp"
    environment:
      - LGSM_GAMESERVERNAME=cssserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_IP=0.0.0.0
      - LGSM_PORT=30015
    volumes:
      - "./logs:/home/linuxgsm/linuxgsm/logs"
