version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - LGSM_GAMESERVERNAME=gmodserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_PORT=27015
      - LGSM_DEFAULTMAP=gm_construct
      - LGSM_GAMEMODE=sandbox
      # - LGSM_HOSTNAME=servername
      # - LGSM_SV_PASSWORD=password
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
