version: '3.3'
volumes:
  saves:
  serverfiles:
services:
  7dtd:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 26900:26900
    environment:
      - LGSM_GAMESERVERNAME=sdtdserver
      - LGSM_SERVERCFGFULLPATHDEFAULT=/home/linuxgsm/linuxgsm/lgsm/config-default/config-game/7DaysToDie/serverconfig.xml
      - LGSM_UPDATEINSTALLSKIP=UPDATE

      # See /config-game-template/7DaysToDie/serverconfig.xml.tmpl for all config options
      - LGSM_PORT=26900

      # DO NOT SET LGSM_SERVER_VISIBILITY TO 0/1. LGSM uses this to check if server is running
      - LGSM_SERVER_VISIBILITY=2

      - LGSM_SERVER_NAME=LGSM Server
      - LGSM_GAME_NAME=My Game
      - LGSM_WORLD_GEN_SEED=ChangeMe
      - LGSM_GAME_WORLD=RWG
      # - LGSM_EAC_ENABLED=false

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      - saves:/home/linuxgsm/linuxgsm/Saves
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
