# This hasn't been tested, Setting the config is'nt overly clear https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/wurmserver/_default.cfg
version: '3.9'
volumes:
  serverfiles:
services:
  wurm:
    image: joshhsoj1902/linuxgsm-docker:latest
    # ports:
    #   - 10027:10027/tcp
    #   - 10027:10027/udp
    environment:
      - LGSM_GAMESERVERNAME=wurmserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
