version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 10027:10027/tcp
      - 10027:10027/udp
    environment:
      - LGSM_GAMESERVERNAME=pstbsserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_PORT=10027
      - LGSM_QUERYPORT=10037
      - LGSM_MAXPLAYERS=80
      - LGSM_NUMRESERVEDSLOTS=2
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
