version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 26900:26900
    environment:
      - LGSM_GAMESERVERNAME=sdtdserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE

      - LGSM_SERVER_PORT=26900
      - LGSM_SERVER_IS_PUBLIC=false
      - LGSM_SERVER_NAME=WorldSeed
      # - LGSM_SERVER_PASSWORD
      # - LGSM_SERVER_MAX_PLAYER_COUNT
      # - LGSM_SERVER_RESERVED_SLOTS
      # - LGSM_SERVER_RESERVED_SLOTS_PERMISSION
      # - LGSM_SERVER_ADMIN_SLOTS
      # - LGSM_SERVER_ADMIN_SLOTS_PERMISSION

      # - LGSM_SERVER_DESCRIPTION
      # - LGSM_SERVER_WEBSITE_URL
      # - LGSM_SERVER_DISABLED_NETWORK_PROTOCOLS

      - LGSM_GAME_WORLD="Navezgane"  # "Random Gen" is better, this is for tests :(
      # - LGSM_GAME_NAME
      # - LGSM_GAME_DIFFICULTY
      # - LGSM_GAME_MODE

      # - LGSM_ZOMBIES_RUN
      # - LGSM_BUILD_CREATE
      # - LGSM_DAY_NIGHT_LENGTH
      # - LGSM_DAY_LIGHT_LENGTH
      # - LGSM_PLAYER_KILLING_MODE
      # - LGSM_PERSISTENT_PLAYER_PROFILES

      # - LGSM_PLAYERS_SAFE_ZONE_LEVEL
      # - LGSM_PLAYERS_SAFE_ZONE_HOURS

      # - LGSM_CONTROL_PANEL_ENABLED
      # - LGSM_CONTROL_PANEL_PORT
      # - LGSM_CONTROL_PANEL_PASSWORD

      # - LGSM_TELNET_ENABLED
      # - LGSM_TELNET_PORT
      # - LGSM_TELNET_PASSWORD

      # - LGSM_ADMIN_FILE_NAME

      # - LGSM_DROP_ON_DEATH
      # - LGSM_DROP_ON_QUIT

      # - LGSM_BLOOD_MOON_ENEMY_COUNT
      # - LGSM_ENEMY_SPAWN_MODE
      # - LGSM_ENEMY_DIFFICULTY

      # - LGSM_BLOCK_DURABILITY_MODIFIER

      # - LGSM_LOOT_ABUNDANCE
      # - LGSM_LOOT_RESPAWN_DAYS

      # - LGSM_LAND_CLAIM_SIZE
      # - LGSM_LAND_CLAIM_DEAD_ZONE
      # - LGSM_LAND_CLAIM_EXPIREY_TIME
      # - LGSM_LAND_CLAIM_DECAY_MODE
      # - LGSM_LAND_CLAIM_ONLINE_DURABILITY_MODIFIER
      # - LGSM_LAND_CLAIM_OFFLINE_DURABILITY_MODIFIER
      # - LGSM_AIR_DROP_FREQUENCY
      # - LGSM_AIR_DROP_MAKER
      # - LGSM_MAX_SPAWNED_ZOMBIES

      # - LGSM_MAX_SPAWNED_ANIMALS
      - LGSM_EAC_ENABLED=false
      # - LGSM_HIDE_COMMAND_EXECUTION_LOG
      # - LGSM_MAX_UNCOVERED_MAP_CHUNK_PER_PLAYER
      # - LGSM_BEDROLL_DEAD_ZONE_SIZE
    volumes:
      - "/home/steam/linuxgsm/logs"
      - "/home/steam/linuxgsm/serverfiles"
