#############################
# SERVER STATUS
#############################
#
# Working: Unsure
# Tested in CI: No
#
# Does this server have save files: Unsure
# Where are save files saved: Unsure, somewhere in `serverfiles`
#
# Configuration:
#  - https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/inssserver/_default.cfg
#
############################

version: '3.3'
volumes:
  serverfiles:
services:
  inss:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 27102:27102/udp
      - 27131:27131/udp
    environment:
      - LGSM_GAMESERVERNAME=inssserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
