#############################
# SERVER STATUS
#############################
#
# Working: Yes
# Tested in CI: Yes
#
# Does this server have save files: No
#
# Configuration:
#  - https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/cssserver/_default.cfg
#
############################

version: '3.3'
volumes:
  serverfiles:
services:
  css:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - LGSM_GAMESERVERNAME=cssserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_PORT=27015

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
