version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - LGSM_GAMESERVERNAME=cssserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_PORT=27015
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
