#############################
# SERVER STATUS
#############################
#
# Working: Unsure
# Tested in CI: No
#
# Does this server have save files: Unsure
# Where are save files saved: Unsure, somewhere in `serverfiles`
#
# Configuration:
#  - https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/inssserver/_default.cfg
#
############################

version: '3.3'
volumes:
  serverfiles:
services:
  pstbs:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 10027:10027/tcp
      - 10027:10027/udp
    environment:
      - LGSM_GAMESERVERNAME=pstbsserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_PORT=10027
      - LGSM_QUERYPORT=10037
      - LGSM_MAXPLAYERS=80
      - LGSM_NUMRESERVEDSLOTS=2
    
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
